name: Bot ios 'algorand on POC-BOT-RN'
on:
  push:
    branches:
      - poc-speculos-mobile-bot

jobs:
  run-bot:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieving coin apps
        uses: actions/checkout@v2
        with:
          repository: LedgerHQ/coin-apps
          token: ${{ secrets.PAT }}
          path: coin-apps
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
      - name: install yarn
        run: npm i -g yarn
      - name: kill apt-get
        run: sudo killall -w apt-get apt || echo OK
      - name: Install linux deps
        run: sudo apt-get install -y libusb-1.0-0-dev jq
      - name: Install dependencies
        run: |
          yarn global add yalc
          yarn --frozen-lockfile
          yarn ci-setup-cli
      - name: LOGGER
        env:
          BOT_LOG_PROXY_FILE: botreport/logs.txt
        run: |
          mkdir botreport
          cd cli
          yarn run botProxyLog -p 8331 &
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: bot-react-native/node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Rebuild detox
        working-directory: bot-react-native
        if: steps.cache.outputs.cache-hit == 'true'
        run: yarn detox clean-framework-cache && yarn detox build-framework-cache
        timeout-minutes: 120     
      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: bot-react-native/ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}
      - name: Update Pods
        working-directory: bot-react-native
        run: |
          gem update cocoapods xcodeproj
          cd ios && pod install && cd ..
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - name: build bot
        working-directory: bot-react-native
        run: yarn detox build e2e --configuration ios
      - name: run test bot
        working-directory: bot-react-native
        run: yarn detox test e2e --configuration ios --cleanup --debug-synchronization 200
      - name: upload logs
        if: failure() || success()
        uses: actions/upload-artifact@v1
        with:
          name: botreport
          path: botreport/
